@testable import MLXLocalModels
import Testing

@Suite("MLX supported architecture registry")
struct MLXSupportedArchitectureTests {
    @Test("registers every copied MLX model family")
    func registersEveryCopiedMLXModelFamily() {
        let registeredTypes = Set(LLMTypeRegistry.shared.registeredModelTypes())

        #expect(Self.expectedTypes.subtracting(registeredTypes).isEmpty)
    }

    private static let expectedTypes: Set<String> = [
        "acereason",
        "afmoe",
        "apertus",
        "baichuan_m1",
        "bailing_moe",
        "bitnet",
        "cohere",
        "deepseek",
        "deepseek_v2",
        "deepseek_v3",
        "deepseek_v32",
        "ernie4_5",
        "exaone",
        "exaone4",
        "falcon_h1",
        "gemma",
        "gemma2",
        "gemma3",
        "gemma3_text",
        "gemma3n",
        "gemma4",
        "gemma4_assistant",
        "gemma4_text",
        "gemma4_unified_assistant",
        "glm4",
        "glm4_moe",
        "glm4_moe_lite",
        "glm_moe_dsa",
        "gpt2",
        "gpt_bigcode",
        "gpt_oss",
        "gpt_neox",
        "granite",
        "granitemoe",
        "granitemoehybrid",
        "helium",
        "internlm2",
        "jamba",
        "jamba_3b",
        "lfm2",
        "lfm2_moe",
        "lille-130m",
        "llama",
        "mamba",
        "mamba2",
        "mimo",
        "mimo_v2_flash",
        "minicpm",
        "minicpm3",
        "minimax",
        "mistral",
        "mistral3",
        "ministral3",
        "nanochat",
        "nemotron_h",
        "olmo",
        "olmo2",
        "olmo3",
        "olmoe",
        "openelm",
        "phi",
        "phi3",
        "phimoe",
        "qwen2",
        "qwen2_moe",
        "qwen3",
        "qwen3_5",
        "qwen3_5_moe",
        "qwen3_5_text",
        "qwen3_moe",
        "qwen3_next",
        "smollm3",
        "stablelm",
        "starcoder2"
    ]
}
